#!/bin/bash
echo "=== V1V2系统完整测试 ==="
echo ""
echo "1. 首页测试:"
curl -s http://localhost:5000/ | grep -o "V1V2成交系统" && echo "✅ 首页包含V1V2模块"
echo ""
echo "2. V1V2监控页测试:"
curl -s http://localhost:5000/v1v2-monitor | grep -o "返回首页" && echo "✅ V1V2监控页包含返回首页按钮"
curl -s http://localhost:5000/v1v2-monitor | grep -o "V1V2设置" && echo "✅ V1V2监控页包含设置按钮"
echo ""
echo "3. V1V2设置页测试:"
curl -s http://localhost:5000/v1v2-settings | grep -o "V1V2阈值设置" && echo "✅ V1V2设置页正常"
echo ""
echo "4. API测试:"
curl -s http://localhost:5000/api/v1v2/latest | python3 -c "import sys,json; data=json.load(sys.stdin); print(f\"✅ V1V2 API返回 {data['count']} 个币种数据\")"
curl -s http://localhost:5000/api/v1v2/settings | python3 -c "import sys,json; data=json.load(sys.stdin); print(f\"✅ V1V2设置API返回 {len(data['settings'])} 个币种配置\")"
echo ""
echo "5. 采集器状态:"
ps aux | grep "v1v2_collector.py" | grep -v grep > /dev/null && echo "✅ V1V2采集器运行中"
echo ""
echo "6. 最新数据:"
tail -3 v1v2_collector.log | grep "本轮采集完成" && echo "✅ 采集器正常工作"
